### ISSUE TITLE
Enterprise archive in apps directory when looseApplication is true

### ISSUE THREAD

**Issue by eharris369** [WASdev/ci.gradle#209]
For the sample.ejb sample, if I update it to use the latest snapshot (2.1.1), it creates an ear in the apps folder of the server instead of a loose application xml file.  In the liberty-plugin-config.xml it has: `<looseApplication>true</looseApplication>` which conflicts with the ear in the apps folder.

I think the problem is with the following in the ejb-ear/build.gradle file:
    apps = [file(ear.archivePath)]
If I change it to this then it creates the xml file as expected:
    apps = [ear]

**Comment by jjvilleg** [comment]
This issue is a bit tricky. So apps = [file(ear.archivePath)] installs the application as a file, so it is expected that the application in dropins will be an ear instead of a looseConfig. While the archive that is installed is an ear, looseApplication is still configured to be true in the project by default, which will only install the applications as looseApp if the archives were generated by the plugin.  In a multi-app project where looseApplication is true, archives that are generated through the war/ear plugin will be installed as looseApplications, while archives that are just copied as files will be installed as-is. We can update the sample project to install the archive using apps = [ear] , but there really isn't much of a workaround when installing files as looseApps

**Comment by eharris369** [comment]
Should there be an error produced during the build to tell the user that apps = [file(ear.archivePath)] and looseApplication are incompatible?

**Comment by jjvilleg** [comment]
I don't think an error is necessary. I think a warning message might work better. Something a long the lines of "Application x was installed as a file instead of a looseApplication. Loose Application is only supported by archives that are generated by a plugin or task"
