### ISSUE TITLE
libertyCreate with configDirectory set requires commons-io (FileUtils)

### ISSUE THREAD

**Issue by jensengelke** [WASdev/ci.gradle#224]
When setting the `configDirectory` property `libertyCreate` fails with

```
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils
        at net.wasdev.wlp.gradle.plugins.tasks.AbstractServerTask.copyConfigFiles(AbstractServerTask.groovy:137)
```

The dependency for `commons-io` at build time should at least be documented (better: removed).

**Comment by mattbsox** [comment]
Gradle doesn’t pull in the transitive dependencies if you’re using a local jar. If you pull the plugin from a repository Gradle will handle them for you. We recommend getting the plugin from a repository rather than referencing a local jar file. You can add this to your build script to get the latest snapshot from Sonatype:
```
buildscript {
    repositories {
        mavenCentral()
        maven {
            name = 'Sonatype Nexus Snapshots'
            url = 'https://oss.sonatype.org/content/repositories/snapshots/'
        }
    }
    dependencies {
        classpath 'net.wasdev.wlp.gradle.plugins:liberty-gradle-plugin:2.1.1-SNAPSHOT'
    }
}
```
This will pull in the plugin and get all of the dependencies. Let us know if the problem persists.

**Comment by cherylking** [comment]
@jensengelke Did Matt's recommendation resolve your issue?

**Comment by jensengelke** [comment]
While I am sure this helps, my issue is that my repository must be an artifactory server that is not connected to the internet to download transitive dependencies.

**Comment by jensengelke** [comment]
I was pointed to https://repo.maven.apache.org/maven2/net/wasdev/wlp/gradle/plugins/liberty-gradle-plugin/2.2/liberty-gradle-plugin-2.2.pom
It lists all the prereqs that need to be loaded in our own repository. The information I was looking for is available.
