### ISSUE TITLE
Facets set to old version for gradle project with 2 web apps

### ISSUE THREAD

**Issue by eharris369** [WASdev/ci.gradle#228]
Unzip the attached project archive and then import the multiServer project into Eclipse as an existing Gradle project.  Once it is imported check the Dynamic Web Module facet version on Web1 and Web2 - it is set to 2.4 instead of 3.0.

If I use net.wasdev.wlp.gradle.plugins:liberty-gradle-plugin:2.1 instead of the latest snapshot then the facet versions get set correctly.

[multiServer.zip](https://github.com/WASdev/ci.gradle/files/1786479/multiServer.zip)

**Comment by mattbsox** [comment]
It ended up being a timing issue based on the order the plugins were getting applied in the project. I  updated the plugin to set the facets after the build files had been fully evaluated.

**Comment by cherylking** [comment]
The reason this regressed is with the addition of ear support, we now check whether the war plugin or the ear plugin are applied before updating the appropriate facet version. Before we simply updated the jst.web facet version without checking for the war plugin. We found if the war plugin were applied before the liberty plugin, the reported issue would not occur. So the fix is to set the facets after the build files have been fully evaluated, as Matt said.
